secret_key = "test"

[auth]
username = "broadcaster"

[stream]
segments_dir = "stream/"

[captcha]
lifetime = 1800
fonts = []
alphabet = "346abegkmprtuwxy"
length = 3
background_color = "#232327"
foreground_color = "#dddddd"

[memory]
states = 32
captchas = 256
chat_messages = 8192
chat_scrollback = 256

[tasks]
rotate_users = 60
rotate_captchas = 60
broadcast_users_update = 4

[names]
broadcaster = "Broadcaster"
anonymous = "Anonymous"

[chat]
max_comment_length = 512
max_name_length = 24
min_name_contrast = 3.0
background_color = "#232327"

[flood]
duration = 20
threshold = 4

[thresholds]
user_notwatching = 8
user_tentative = 20
user_absent = 360
nojs_chat_timeout = 30
