secret_key = "place secret key here"

[control]
address = "control.sock"

[auth]
username = "broadcaster"

[segments]
directory = "stream/"
playlist = "stream.m3u8"
playlist_stale_threshold = 8.0
playlist_cache_lifetime = 0.2
search_cooldown = 0.25
search_timeout = 5.0
stream_initial_buffer = 3

[title]
file = "title.txt"
file_cache_lifetime = 0.5

[captcha]
lifetime = 1800
fonts = []
alphabet = "346abegkmprtuwxy"
length = 3
background_color = "#232327"
foreground_color = "#dddddd"

[memory]
states = 32
captchas = 256
chat_messages = 8192
chat_scrollback = 256

[tasks]
rotate_users = 60.0
rotate_captchas = 60.0
rotate_websockets = 2.0
broadcast_ping = 8.0
broadcast_users_update = 4.0
broadcast_stream_info_update = 3.0

[names]
broadcaster = "Broadcaster"
anonymous = "Anonymous"

[chat]
max_comment_length = 512
max_name_length = 24
min_name_contrast = 3.0
background_color = "#232327"
legacy_tripcode_algorithm = false

[flood.messages]
duration = 20.0
threshold = 4

[flood.lines]
duration = 20.0
threshold = 20

[thresholds]
user_notwatching = 8.0
user_tentative = 20.0
user_absent = 360.0
nojs_chat_timeout = 30.0
