secret_key = "test"

[auth]
username = "broadcaster"

[stream]
segments_dir = "stream/"

[names]
broadcaster = "Broadcaster"
anonymous = "Anonymous"

[chat]
max_comment_length = 512
max_name_length = 24
min_name_contrast = 3.0
background_color = "#232327"

[memory]
notices = 32
chat_messages = 8192
chat_scrollback = 256

[ratelimits]
user_absence = 8
captcha_expiry = 8

[thresholds]
idle = 12
absent = 1800
